[tools]
ripgrep = { version = "latest", exe = "rg" }
rust = "latest"
node = "latest"
go = "latest"
deno = "latest"
glow = "latest"
uv = "latest"
starship = "latest"
ttyd = "latest"
vhs = "0.7.2"
ripgrep-all = "latest"
fzf = "latest"
"go:github.com/laurent22/massren" = "latest"
"go:github.com/x-motemen/ghq" = "latest"
"go:github.com/xconstruct/go-pushbullet/examples/pushb" = "latest"
"go:github.com/variadico/noti/cmd/noti" = "latest"
"go:github.com/atotto/clipboard/cmd/gopaste" = "latest"
"go:github.com/atotto/clipboard/cmd/gocopy" = "latest"
"go:github.com/gsamokovarov/jump" = "latest"
"go:github.com/wincent/clipper" = "latest"
universal-ctags = "latest"
neovim = "nightly"
cargo-binstall = "latest"
yt-dlp = "latest"
hub = "latest"
pnpm = "latest"
jq = "latest"
delta = "latest"
"github:astral-sh/cargo-dist" = { version = "v0.28.7" }
"github:crate-ci/typos" = "latest"
"github:atuinsh/atuin" = "latest"
"npm:@github/copilot" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:editprompt" = "latest"
"pipx:pyright" = "latest"
"aqua:tstack/lnav" = "latest"
usage = "latest"
#"npm:@markwhen/mw" = "latest"
#"npm:@mizchi/readability" = "latest"
#"npm:github:ompugao/readability@branch:feat/fetch_behind_proxy" = "latest"
"pipx:oraios/serena" = "latest"

[settings]
experimental = true
go_set_gobin = true

[alias]
universal-ctags = "https://github.com/ompugao/mise-universal-ctags.git"
neovim = "https://github.com/richin13/asdf-neovim.git"
